package beacon

const (
	BEACON_BLOCK_HEADER_NUM_FIELDS = uint64(5)

	BEACON_BLOCK_HEADER_TREE_HEIGHT = uint64(3)
	BEACON_STATE_TREE_HEIGHT        = uint64(5)
	BALANCE_TREE_HEIGHT             = uint64(38)
	VALIDATOR_TREE_HEIGHT           = uint64(40)

	STATE_ROOT_INDEX = uint64(3)

	VALIDATORS_INDEX = uint64(11)
	BALANCES_INDEX   = uint64(12)

	VALIDATOR_FIELDS_LENGTH = uint64(8)

	VALIDATOR_PUBKEY_INDEX                 = uint64(0)
	VALIDATOR_WITHDRAWAL_CREDENTIALS_INDEX = uint64(1)
	VALIDATOR_BALANCE_INDEX                = uint64(2)
	VALIDATOR_SLASHED_INDEX                = uint64(3)
	VALIDATOR_EXIT_EPOCH_INDEX             = uint64(6)

	SECONDS_PER_SLOT  = uint64(12)
	SLOTS_PER_EPOCH   = uint64(32)
	SECONDS_PER_EPOCH = SECONDS_PER_SLOT * SLOTS_PER_EPOCH

	FAR_FUTURE_EPOCH = ^uint64(0)
	UINT64_MASK      = 0xffffffffffffffff
)
